### ISSUE TITLE
Not dropping the .pdb file.

### ISSUE THREAD

**Issue by SleekZ** [BerkanYildiz/Microsoft.PdbDownloader#1]
Hey, I tried to drag a .sys file onto the .exe but it doesn't even do anything. I've tried building it myself and using your .exe in releases.

Windows ver = 1909

**Comment by BerkanYildiz** [comment]
Depending on your network, it might take a lot of time.
On a remote server, ntoskrnl takes around 10-15 seconds to download.
On my own PC it's extremely quick as I have very good internet.
Make sure you're copying the .sys file to a public directory first, like your desktop. (Otherwise you would have to run in Administrator mode, but in that mode, Drag-n-Drop wont work, it is how it is, I'll try to exploit another some day)

Also, this only works with Microsoft's drivers (ntoskrnl.exe, disk.sys, ndis.sys, etc...), _obviously_, not drivers from NVIDIA, or any other companies.

You can also run the project in Debug Mode and see if any exceptions is being thrown in the "Debug Output" window (it's in Debug > Windows > Output). 

![image](https://user-images.githubusercontent.com/15068742/98371235-1f49f800-203c-11eb-9fd1-ceeac99b689c.png)

**Comment by SleekZ** [comment]
Thanks for the reply! I try them out.
